name: meal_app
description: App de receitas usando MealDB API e backend PHP

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Gerenciamento de estado - GetX
  get: ^4.6.5
  
  # HTTP requests
  http: ^1.2.0
  
  # Cache de imagens
  cached_network_image: ^3.3.1
  
  # Armazenamento local
  shared_preferences: ^2.2.3
  
  # SQLite
  sqflite: ^2.3.3+1
  path: ^1.9.0
  
  # UI
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/